project_id = "gebygucrpipaufrlyqqj"

[functions.send-employee-invitation]
verify_jwt = false

[functions.send-appointment-reminder]
verify_jwt = false

[functions.stock-alert]
verify_jwt = false

[functions.process-notification-queue]
verify_jwt = false
